# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_rash.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(619, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.l_name = QtWidgets.QLineEdit(self.centralwidget)
        self.l_name.setGeometry(QtCore.QRect(10, 40, 601, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_name.setFont(font)
        self.l_name.setText("")
        self.l_name.setObjectName("l_name")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.bt_add = QtWidgets.QPushButton(self.centralwidget)
        self.bt_add.setGeometry(QtCore.QRect(10, 172, 91, 31))
        self.bt_add.setObjectName("bt_add")
        self.bt_close = QtWidgets.QPushButton(self.centralwidget)
        self.bt_close.setGeometry(QtCore.QRect(520, 170, 91, 31))
        self.bt_close.setObjectName("bt_close")
        self.s_price = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.s_price.setGeometry(QtCore.QRect(80, 110, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.s_price.setFont(font)
        self.s_price.setMaximum(1e+18)
        self.s_price.setObjectName("s_price")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 110, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.s_col = QtWidgets.QSpinBox(self.centralwidget)
        self.s_col.setGeometry(QtCore.QRect(480, 110, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.s_col.setFont(font)
        self.s_col.setMaximum(1000000000)
        self.s_col.setProperty("value", 1)
        self.s_col.setObjectName("s_col")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 619, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Название:"))
        self.bt_add.setText(_translate("MainWindow", "Добавить"))
        self.bt_close.setText(_translate("MainWindow", "Отмена"))
        self.label_2.setText(_translate("MainWindow", "Цена:"))
        self.label_3.setText(_translate("MainWindow", "Количество:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
