# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_worker.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(506, 304)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_sur = QtWidgets.QLineEdit(self.centralwidget)
        self.line_sur.setGeometry(QtCore.QRect(30, 60, 131, 21))
        self.line_sur.setObjectName("line_sur")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line_name = QtWidgets.QLineEdit(self.centralwidget)
        self.line_name.setGeometry(QtCore.QRect(190, 60, 131, 21))
        self.line_name.setObjectName("line_name")
        self.line_ot = QtWidgets.QLineEdit(self.centralwidget)
        self.line_ot.setGeometry(QtCore.QRect(360, 60, 131, 21))
        self.line_ot.setText("")
        self.line_ot.setObjectName("line_ot")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.bt_add = QtWidgets.QPushButton(self.centralwidget)
        self.bt_add.setGeometry(QtCore.QRect(30, 180, 91, 31))
        self.bt_add.setObjectName("bt_add")
        self.bt_close = QtWidgets.QPushButton(self.centralwidget)
        self.bt_close.setGeometry(QtCore.QRect(400, 190, 91, 31))
        self.bt_close.setObjectName("bt_close")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.s_procent = QtWidgets.QSpinBox(self.centralwidget)
        self.s_procent.setGeometry(QtCore.QRect(240, 110, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.s_procent.setFont(font)
        self.s_procent.setMaximum(100)
        self.s_procent.setObjectName("s_procent")
        self.l_exception = QtWidgets.QLabel(self.centralwidget)
        self.l_exception.setGeometry(QtCore.QRect(30, 220, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.l_exception.setFont(font)
        self.l_exception.setText("")
        self.l_exception.setObjectName("l_exception")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 506, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Фамилия"))
        self.label_2.setText(_translate("MainWindow", "Имя"))
        self.label_3.setText(_translate("MainWindow", "Отчество"))
        self.bt_add.setText(_translate("MainWindow", "Добавить"))
        self.bt_close.setText(_translate("MainWindow", "Отмена"))
        self.label_4.setText(_translate("MainWindow", "Процент за услуги:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
