# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'more_sale.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(596, 336)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_sur = QtWidgets.QLineEdit(self.centralwidget)
        self.line_sur.setGeometry(QtCore.QRect(10, 40, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.line_sur.setFont(font)
        self.line_sur.setText("")
        self.line_sur.setObjectName("line_sur")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.bt_add = QtWidgets.QPushButton(self.centralwidget)
        self.bt_add.setGeometry(QtCore.QRect(10, 240, 91, 31))
        self.bt_add.setObjectName("bt_add")
        self.bt_close = QtWidgets.QPushButton(self.centralwidget)
        self.bt_close.setGeometry(QtCore.QRect(500, 238, 91, 31))
        self.bt_close.setObjectName("bt_close")
        self.db_price = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.db_price.setGeometry(QtCore.QRect(160, 110, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.db_price.setFont(font)
        self.db_price.setMaximum(1e+18)
        self.db_price.setObjectName("db_price")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.s_col = QtWidgets.QSpinBox(self.centralwidget)
        self.s_col.setGeometry(QtCore.QRect(160, 180, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.s_col.setFont(font)
        self.s_col.setMinimum(-1000000000)
        self.s_col.setMaximum(1000000000)
        self.s_col.setObjectName("s_col")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 596, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Название:"))
        self.bt_add.setText(_translate("MainWindow", "Готово"))
        self.bt_close.setText(_translate("MainWindow", "Отмена"))
        self.label_2.setText(_translate("MainWindow", "Базовая цена:"))
        self.label_3.setText(_translate("MainWindow", "В наличии:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
